apiVersion: v1
kind: Namespace
metadata:
  name: k8s-namespace 

---
apiVersion: v1
kind: Pod
metadata:
  name: k8s-pod  
  namespace: k8s-namespace  
spec:
  containers:
  - name: k8s-container
    image: k8s:1.0
    imagePullPolicy: Never 
    ports:
    - containerPort: 80
